const $=id=>document.getElementById(id);const fileInput=$('csvFile'),assetInput=$('asset'),tfInput=$('timeframe'),importBtn=$('importBtn');let selectedFile=null,parsedCandles=[];
const aliases={open:['open','o','<open>'],high:['high','h','<high>'],low:['low','l','<low>'],close:['close','c','<close>'],date:['date','<date>','datetime','timestamp','time']};const norm=s=>String(s??'').trim().toLowerCase().replace(/^['"]|['"]$/g,'').replace(/\s+/g,'').replace(/_/g,'');function detect(h,t){return h.findIndex(x=>aliases[t].includes(norm(x))||norm(x).includes(t))}function split(s,d){return s.split(d).map(x=>x.trim().replace(/^['"]|['"]$/g,''))}
function parse(text){let lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw Error('Not enough rows.');let d=lines[0].includes('\t')?'\t':lines[0].includes(';')?';':',';let h=split(lines[0],d),i={open:detect(h,'open'),high:detect(h,'high'),low:detect(h,'low'),close:detect(h,'close'),date:detect(h,'date')};for(let k of ['open','high','low','close'])if(i[k]<0)throw Error('Missing '+k.toUpperCase()+' column.');let a=[];for(let n=1;n<lines.length;n++){let r=split(lines[n],d),v=['open','high','low','close'].map(k=>Number(r[i[k]]));if(v.every(Number.isFinite)&&v[2]<=v[1])a.push({index:n,date:i.date>=0?(r[i.date]||''):'',open:v[0],high:v[1],low:v[2],close:v[3]})}if(!a.length)throw Error('No valid OHLC rows found.');return a}
function features(a){return a.map((c,i)=>{let p=a[i-1],range=Math.max(0,c.high-c.low),body=Math.abs(c.close-c.open),up=Math.max(0,c.high-Math.max(c.open,c.close)),lo=Math.max(0,Math.min(c.open,c.close)-c.low);let f={...c,direction:c.close>c.open?'Bullish':c.close<c.open?'Bearish':'Doji',range,bodyPercent:range?body/range*100:0,upperWickPercent:range?up/range*100:0,lowerWickPercent:range?lo/range*100:0,closePosition:!range?'Middle 60%':c.close>=c.low+range*.8?'Top 20%':c.close<=c.low+range*.2?'Bottom 20%':'Middle 60%'};if(!p)return {...f,previousHighTaken:null,previousLowTaken:null,closedAbovePreviousHigh:null,closedBelowPreviousLow:null};return {...f,previousHighTaken:c.high>=p.high,previousLowTaken:c.low<=p.low,closedAbovePreviousHigh:c.close>p.high,closedBelowPreviousLow:c.close<p.low}})}
const DB='CandleProbabilityDB2';function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('datasets',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function put(x){let d=await openDB();return new Promise((res,rej)=>{let t=d.transaction('datasets','readwrite');t.objectStore('datasets').put(x);t.oncomplete=res;t.onerror=()=>rej(t.error)})}async function all(){let d=await openDB();return new Promise((res,rej)=>{let r=d.transaction('datasets').objectStore('datasets').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function yn(v){return v==null?'—':v?'Yes':'No'}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
const choices={direction:['','Bullish','Bearish','Doji'],yn:['','Yes','No'],position:['','Top 20%','Middle 60%','Bottom 20%']};const fields=[['direction','Direction','direction'],['previousHighTaken','Took previous high','yn'],['previousLowTaken','Took previous low','yn'],['closedAbovePreviousHigh','Closed above previous high','yn'],['closedBelowPreviousLow','Closed below previous low','yn'],['closePosition','Close position','position']];let candleCount=2;
function selectHTML(name,label,type){return `<label>${label}<select data-field="${name}">${choices[type].map(x=>`<option value="${x}">${x||'Any'}</option>`).join('')}</select></label>`}
function drawBuilder(){let box=$('candleBuilder');box.innerHTML='';for(let n=1;n<=candleCount;n++){let card=document.createElement('div');card.className='candle-card';card.innerHTML=`<h3>C${n}</h3><div class="fields">${fields.map(f=>selectHTML(f[0],f[1],f[2])).join('')}</div>`;box.appendChild(card)}$('builderCount').textContent=`${candleCount} candle${candleCount>1?'s':''}`;$('addCandleBtn').style.display=candleCount>=5?'none':'inline-block';$('addCandleBtn').textContent=`+ Add C${candleCount+1}`}
$('addCandleBtn').onclick=()=>{if(candleCount<5){candleCount++;drawBuilder()}};
function matchPattern(ds,pattern){let c=ds.candles,need=pattern.length,matches=[];for(let i=1;i<=c.length-need;i++){let ok=true;for(let j=0;j<need;j++){let x=c[i+j],q=pattern[j];for(let [k,v] of Object.entries(q))if(v&&String(x[k])!==v){ok=false;break}if(!ok)break}if(ok)matches.push(i)}return matches}
$('predictBtn').onclick=async()=>{let datasets=await all();if(!datasets.length){$('matchResult').className='result bad';$('matchResult').textContent='Import a dataset first.';return}let pattern=[...document.querySelectorAll('.candle-card')].map(card=>{let q={};card.querySelectorAll('select').forEach(s=>{if(s.value)q[s.dataset.field]=s.value});return q});if(pattern.every(x=>Object.keys(x).length===0)){ $('matchResult').className='result bad';$('matchResult').textContent='Select at least one condition.';return}let total=0,by=[];for(let d of datasets){let m=matchPattern(d,pattern);if(m.length){total+=m.length;by.push(`${d.asset} • ${d.timeframe}: ${m.length.toLocaleString()}`)}}$('matchResult').className=total?'result good':'result bad';$('matchResult').innerHTML=total?`<strong>${total.toLocaleString()} historical matches found</strong><br><small>${by.join(' &nbsp; | &nbsp; ')}</small>`:'No historical matches found. Try removing a condition.'};
fileInput.onchange=async()=>{selectedFile=fileInput.files[0];importBtn.disabled=true;if(!selectedFile)return;try{parsedCandles=parse(await selectedFile.text());$('fileStatus').className='status good';$('fileStatus').textContent=`✓ ${parsedCandles.length.toLocaleString()} candles detected • OHLC ready`;importBtn.disabled=false}catch(e){$('fileStatus').className='status bad';$('fileStatus').textContent=e.message}};
importBtn.onclick=async()=>{try{let c=features(parsedCandles),ds={id:crypto.randomUUID(),asset:assetInput.value.trim()||'Unknown',timeframe:tfInput.value.trim()||'Unknown',filename:selectedFile.name,candleCount:c.length,importedAt:new Date().toISOString(),candles:c};await put(ds);render(ds);await renderDatasets();$('fileStatus').className='status good';$('fileStatus').textContent=`✓ Imported ${c.length.toLocaleString()} candles • features calculated`;fileInput.value='';selectedFile=null;parsedCandles=[];importBtn.disabled=true}catch(e){$('fileStatus').className='status bad';$('fileStatus').textContent='Import failed: '+e.message}};
async function renderDatasets(){let a=await all();$('datasetCount').textContent=a.length;$('datasets').innerHTML=a.length?a.slice().reverse().map(d=>`<div class="dataset"><div><strong>${esc(d.asset)} • ${esc(d.timeframe)}</strong><small>${d.candleCount.toLocaleString()} candles • ${esc(d.filename)}</small></div><span class="badge">Features ready</span></div>`).join(''):'<div class="empty">No datasets imported yet.</div>'}
function render(d){$('featureSection').hidden=false;$('featureTitle').textContent=`${d.asset} • ${d.timeframe} — candle features`;$('featureTableBody').innerHTML=d.candles.slice(-50).reverse().map(c=>`<tr><td>${esc(c.date||c.index)}</td><td>${c.open}</td><td>${c.high}</td><td>${c.low}</td><td>${c.close}</td><td>${c.direction}</td><td>${yn(c.previousHighTaken)}</td><td>${yn(c.previousLowTaken)}</td><td>${yn(c.closedAbovePreviousHigh)}</td><td>${yn(c.closedBelowPreviousLow)}</td><td>${c.closePosition}</td></tr>`).join('')}
drawBuilder();(async()=>{try{let a=await all();await renderDatasets();if(a.length)render(a[a.length-1])}catch(e){console.error(e)}})();
