const $=id=>document.getElementById(id);
const fileInput=$('csvFile'),assetInput=$('asset'),tfInput=$('timeframe'),importBtn=$('importBtn');
let selectedFile=null,parsedCandles=[];
const aliases={open:['open','o','<open>'],high:['high','h','<high>'],low:['low','l','<low>'],close:['close','c','<close>'],date:['date','<date>','datetime','timestamp','time']};
function normalize(s){return String(s??'').trim().toLowerCase().replace(/^['"]|['"]$/g,'').replace(/\s+/g,'').replace(/_/g,'')}
function detect(headers,type){const w=aliases[type];return headers.findIndex(h=>w.includes(normalize(h))||normalize(h).includes(type))}
function splitLine(line,d){return line.split(d).map(x=>x.trim().replace(/^['"]|['"]$/g,''))}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw Error('The file does not contain enough rows.');const d=lines[0].includes('\t')?'\t':lines[0].includes(';')?';':',';const h=splitLine(lines[0],d),idx={open:detect(h,'open'),high:detect(h,'high'),low:detect(h,'low'),close:detect(h,'close'),date:detect(h,'date')};for(const k of ['open','high','low','close'])if(idx[k]<0)throw Error(`Could not find ${k.toUpperCase()} column.`);const a=[];for(let i=1;i<lines.length;i++){const r=splitLine(lines[i],d),n=['open','high','low','close'].map(k=>Number(r[idx[k]]));if(n.every(Number.isFinite)&&n[2]<=n[1])a.push({index:i,date:idx.date>=0?(r[idx.date]||''):'',open:n[0],high:n[1],low:n[2],close:n[3]})}if(!a.length)throw Error('No valid OHLC rows were found.');return a}
function addFeatures(a){return a.map((c,i)=>{const p=a[i-1],range=Math.max(0,c.high-c.low),body=Math.abs(c.close-c.open),upper=Math.max(0,c.high-Math.max(c.open,c.close)),lower=Math.max(0,Math.min(c.open,c.close)-c.low),direction=c.close>c.open?'Bullish':c.close<c.open?'Bearish':'Doji',closePosition=range===0?'Middle 60%':c.close>=c.low+range*.8?'Top 20%':c.close<=c.low+range*.2?'Bottom 20%':'Middle 60%',f={...c,direction,range,bodyPercent:range?body/range*100:0,upperWickPercent:range?upper/range*100:0,lowerWickPercent:range?lower/range*100:0,closePosition};if(!p)return {...f,previousHighTaken:null,previousLowTaken:null,closedAbovePreviousHigh:null,closedBelowPreviousLow:null,closedInsidePreviousRange:null,openAbovePreviousClose:null,openBelowPreviousClose:null,closeAbovePreviousClose:null,closeBelowPreviousClose:null};return {...f,previousHighTaken:c.high>=p.high,previousLowTaken:c.low<=p.low,closedAbovePreviousHigh:c.close>p.high,closedBelowPreviousLow:c.close<p.low,closedInsidePreviousRange:c.close<=p.high&&c.close>=p.low,openAbovePreviousClose:c.open>p.close,openBelowPreviousClose:c.open<p.close,closeAbovePreviousClose:c.close>p.close,closeBelowPreviousClose:c.close<p.close}})}
const DB_NAME='CandleProbabilityDB',STORE='datasets';
function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbPut(ds){const db=await dbOpen();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(ds);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function dbAll(){const db=await dbOpen();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
fileInput.addEventListener('change',async()=>{selectedFile=fileInput.files[0];importBtn.disabled=true;parsedCandles=[];if(!selectedFile){$('fileStatus').textContent='No file selected';return}try{parsedCandles=parseCSV(await selectedFile.text());$('fileStatus').className='status good';$('fileStatus').textContent=`✓ ${parsedCandles.length.toLocaleString()} candles detected • OHLC ready`;importBtn.disabled=false}catch(e){$('fileStatus').className='status bad';$('fileStatus').textContent=e.message}});
importBtn.addEventListener('click',async()=>{if(!parsedCandles.length)return;try{const features=addFeatures(parsedCandles),ds={id:crypto.randomUUID(),asset:assetInput.value.trim()||'Unknown',timeframe:tfInput.value.trim()||'Unknown',filename:selectedFile.name,candleCount:features.length,importedAt:new Date().toISOString(),candles:features};await dbPut(ds);await renderDatasets();renderFeatureTable(ds);$('fileStatus').className='status good';$('fileStatus').textContent=`✓ Imported ${features.length.toLocaleString()} candles • features calculated`;fileInput.value='';selectedFile=null;parsedCandles=[];importBtn.disabled=true}catch(e){$('fileStatus').className='status bad';$('fileStatus').textContent=`Import failed: ${e.message||e}`}});
async function renderDatasets(){const all=await dbAll();$('datasetCount').textContent=all.length;const box=$('datasets');if(!all.length){box.className='empty';box.textContent='No datasets imported yet.';return}box.className='';box.innerHTML=all.slice().reverse().map(d=>`<div class="dataset"><div><strong>${escapeHtml(d.asset)} • ${escapeHtml(d.timeframe)}</strong><small>${d.candleCount.toLocaleString()} candles • ${escapeHtml(d.filename)}</small></div><span class="badge">Features ready</span></div>`).join('')}
function renderFeatureTable(ds){const section=$('featureSection');section.hidden=false;$('featureTitle').textContent=`${ds.asset} • ${ds.timeframe} — candle features`;$('featureTableBody').innerHTML=ds.candles.slice(-50).reverse().map(c=>`<tr><td>${escapeHtml(c.date||String(c.index))}</td><td>${c.open}</td><td>${c.high}</td><td>${c.low}</td><td>${c.close}</td><td>${c.direction}</td><td>${yn(c.previousHighTaken)}</td><td>${yn(c.previousLowTaken)}</td><td>${yn(c.closedAbovePreviousHigh)}</td><td>${yn(c.closedBelowPreviousLow)}</td><td>${c.closePosition}</td></tr>`).join('')}
function yn(v){return v===null?'—':v?'Yes':'No'}function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
(async()=>{try{const all=await dbAll();await renderDatasets();if(all.length)renderFeatureTable(all[all.length-1])}catch(e){console.error(e)}})();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
